name: run tests

on: pull_request

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run tests
